### ISSUE TITLE
Question: What is the difference of vim-CtrlXA vs. other in-/decrement plugins?

### ISSUE THREAD

**Issue by kiryph** [Konfekt/vim-CtrlXA#1]
There are already plenty of `<C-X/A>` plugins such as

- https://github.com/bootleq/vim-cycle
- https://github.com/mjbrownie/swapit
- https://github.com/AndrewRadev/switch.vim#more-complicated-mappings
- https://github.com/nishigori/increment-activator
- https://github.com/zef/vim-cycle
- ...

What is the difference of this plugin compared to the others?

**Comment by Konfekt** [comment]
I did not check every single one of them. But those that I tried had some bugs, did not respect `.` and were confusingly written. The aim of this plug-in was to have something stable, respecting `.` (with `vim-repeat`) and cleanly written (taking a look at the function underlying the mappings to `Ctrl-X/A` in `autoload\CtrlXA.vim`, it has only a couple of lines).

**Comment by kiryph** [comment]
Thanks for sharing your motivation. I can see that your plugin is really minimalistic (cloc says 23+15 lines of code) which is certainly a good thing.

I tried myself `vim-cycle` by bootleq and `swapit` by mjbrownie and sticked to `vim-cycle` even though I had some troubles to configure it the way I wanted (https://github.com/bootleq/vim-cycle/issues/6, https://github.com/bootleq/vim-cycle/issues/5, https://github.com/bootleq/vim-cycle/issues/4).

### Comparison

1. **vim-cycle by bootleq**  

- dot-repeat
- ft-specific toggles
- support for pairs in LaTeX, e.g. `\big( a + b \big)` to `\Big( a +b \Big)`
- options such as `match_case`, `hard_case`, `match_word`
- Fallback mappings to vim-speeddating are possible even though I have uninstalled speeddating because I don't use it enough.

Stats:
```
❯ cloc --by-file vim-cycle
       8 text files.
       8 unique files.
       5 files ignored.

github.com/AlDanial/cloc v 1.72  T=0.07 s (73.1 files/s, 12668.2 lines/s)
-------------------------------------------------------------------------------------
File                                              blank        comment           code
-------------------------------------------------------------------------------------
vim-cycle/autoload/cycle.vim                        124             20            559
vim-cycle/plugin/cycle.vim                           20              8             45
vim-cycle/README.md                                  11              0             31
vim-cycle/test/group_operation.vim                    4              0             23
vim-cycle/CHANGES.md                                 10              0             12
-------------------------------------------------------------------------------------
SUM:                                                169             28            670
-------------------------------------------------------------------------------------
```

2. **swapit**
- dot-repeat (https://github.com/mjbrownie/swapit/pull/23)
- ft-specific toggles
- Fallback to vim-speeddating possible.
- no support for pairs and customizations such as `match_case`, `hard_case`, `match_word`

Stats:
```
❯ cloc --by-file swapit
      13 text files.
      12 unique files.
       4 files ignored.

github.com/AlDanial/cloc v 1.72  T=0.08 s (123.7 files/s, 7210.2 lines/s)
----------------------------------------------------------------------------------------------
File                                                       blank        comment           code
----------------------------------------------------------------------------------------------
swapit/plugin/swapit.vim                                      47            201            239
swapit/autoload/cssswapit.vim                                 10              2             28
swapit/after/ftplugin/htmldjango_swapit.vim                    2              1             10
swapit/after/ftplugin/tex_swapit.vim                           1              0              9
swapit/after/ftplugin/html_swapit.vim                          2              1              8
swapit/after/ftplugin/css_swapit.vim                           2              0              6
swapit/after/ftplugin/python_swapit.vim                        0              0              3
swapit/after/ftplugin/php_swapit.vim                           0              0              3
swapit/after/ftplugin/vim_swapit.vim                           3              1              2
swapit/after/ftplugin/gitrebase_swapit.vim                     0              0              2
----------------------------------------------------------------------------------------------
SUM:                                                          67            206            310
----------------------------------------------------------------------------------------------
```

3. **vim-CtrlXA**

- dot-repeat
- super minimalistic

stats:
```
❯ cloc --by-file vim-CtrlXA
       4 text files.
       4 unique files.
       2 files ignored.

github.com/AlDanial/cloc v 1.72  T=0.04 s (72.0 files/s, 1584.5 lines/s)
---------------------------------------------------------------------------------
File                                          blank        comment           code
---------------------------------------------------------------------------------
vim-CtrlXA/plugin/CtrlXA.vim                      5              0             23
vim-CtrlXA/README.md                              3              0             17
vim-CtrlXA/autoload/CtrlXA.vim                    2              1             15
---------------------------------------------------------------------------------
SUM:                                             10              1             55
---------------------------------------------------------------------------------
```

**Comment by Konfekt** [comment]
Thanks for the comparison!

Ok, I recall trying swapit.vim and its quirks made me create vim-CtrlXA. 

Perhaps vim-cycle is a rock solid alternative that offers a lot more customization that I might try out in the future. There hasn't any need yet though, for example the TeX delimiter cycling the plugin vimtex already takes care of.

**Comment by Konfekt** [comment]
The lack of file-type specific cycles is made up by the latest commit at the cost of an extra line of code (and some in the docs).

**Comment by Konfekt** [comment]
Regarding 

> Fallback to vim-speeddating 

this has also been documented recently.
