### ISSUE TITLE
<Ctrl-X> and <Ctrl-A> don't move cursor

### ISSUE THREAD

**Issue by mgarort** [Konfekt/vim-CtrlXA#12]
First of all, thanks a lot for the great plugin! It's very useful.

This issue is related to #10 I believe.

The problem is that `<Ctrl-x>` and `<Ctrl-a>` keep the cursor where it is, instead of moving it to the next iterable to toggle. This is different from Vim's native behaviour (I think).

Moving the cursor to the iterable is very handy, and I use it often for things like changing `day number is 10 and day name is Saturday` to `day number is 11 and day name is Sunday`. If the cursor starts at the beginning of the line, and I doing `<Ctrl-a>` moves it to the iterable, then going from the sentence on the left to the sentence on the right only requires `<Ctrl-a><l><Ctrl-a>`. But if `<Ctrl-a` keeps the cursor quiet, then we have to: 1) do  `<Ctrl-a>`, 2) manually move the cursor to after the first iterable (which could be more or less keystrokes depending on the sentence), and 3) do `<Ctrl-a>` again.

Thanks in advance.

**Comment by Konfekt** [comment]
More exactly, it is about this comment https://github.com/Konfekt/vim-CtrlXA/issues/10#issuecomment-674052762 in #10.

It is a matter of taste. The change was introduced on behest of #8 and #10 was fine with it. As am I. 

I turned it into an option that is turned off by default.

However, the given example `day number is 10 and day name is Saturday ` does not illustrate the issue: Vim's native behavior was kept: the cursor keeps moving when a number is incremented or decremented by `<C-X/A>`. 
The cursor only stays where it is when a word of `g:CtrlXA_toggles` is incremented or decremented.

**Comment by mgarort** [comment]
Hi @Konfekt 

Thank you so much! It works perfectly.

I'll close this issue now.
