### ISSUE TITLE
How are iterable characters separated?

### ISSUE THREAD

**Issue by mgarort** [Konfekt/vim-CtrlXA#13]
I found an interesting example where the separation of iterable characters did not seem intuitive. I am trying to find the maximum coordinates (x, y z) from a file, so I have a variable called `x` and variable called `max_x`.

- If I press `<C-a>` on `x`, it gets increased to `y`, as expected.
- However, if I press `<C-a>` on the last `x` of `max_x`, the cursor skips the current `x` and jumps to the next iterable character, increasing that iterable character instead.

In this example, the problem seems to be that the underscore `_` does not work as a delimiter for iterable characters, but for people using `snake_case` like me it makes sense to use the underscore as a delimiter.

What are the rules to separate iterable characters? And can these rules be customized?

Thanks! And thanks for the great plugin, I use it daily :)

**Comment by Konfekt** [comment]
The separation is determined by `&iskeyword`. Depending on the programming language, file type, `&iskeyword` contains or misses `_`. For this plug-in, removing `_` from `&iskeyword` would resolve your issue, but then completion `:h ins-completion` will no longer complete those characters.

One could think about forcefully changing `&iskeyword` to contain only `[a-zA-Z0-9]` at the beginning of 

```vim
" autoload/CtrlXA.vim (line 1)
function! CtrlXA#SingleInc(key) abort
```

and reverting at the end of it, but this restricts the choices of keyword toggles. 
Best would be a function that collects just the characters `...` that appear in the keyword toggles; then `&keyword` could be replaced by `[...]`.

**Comment by mgarort** [comment]
I see... Perhaps the function could collect:

- As a default, the values from `iskeyword`. Most people will be happy with this default and won't feel the need to change it.
- As customization, the values of one list of characters that should be considered toggle delimiters, and the values of another list of characters that should not be considered toggle delimiters. Maybe called something like `custom_delimiters = [...]` or `removed_nondelimiters = [...]` (probably better names exist, but just to convey the idea). This would give users the opportunity to tune the toggle separation if they really want to.

Of this interface, I like the fact that there would be a flexible default that works well in most cases, and I don't like the fact that there would be two different custom lists. But perhaps it is fine to have two different lists because users who customize these lists will probably know what they are doing.

A simple version could be implemented with `:h index()`, `:h add()` and `:h remove()`, I think.

**Comment by mgarort** [comment]
Ok, another idea: if we work under the assumption that users who customize the toggles know what they are doing, then the toggle delimiters could be set with a single list called e.g. `toggle_delimiters`:
- As a default, `toggle_delimiters` could collect the values from `iskeyword`.
- As customization, `toggle_delimiters` could be set manually by the user in the `ftplugin` directory. This way, they could set the toggle delimiters for each filetype without breaking the default behaviour for other filetypes, which would remain to be defined by `iskeyword` in those filetypes.

I think this approach is better than the previous one because it uses a single custom list instead of two custom lists.

**Comment by Konfekt** [comment]
Yes, it is. In any case we work with positives, only a list of keyword characters replacing `&iskeyword`. I added your last point, but know of no reference for such a character collection function in your first point. Any hint or pull request is welcome.

**Comment by mgarort** [comment]
I have created a pull request with what I meant (just something simple like `CtrlXA_iskeyword = &l:iskeyword`). It is my first ever pull request to a Vim plugin, so if something is wrong or unclear feel free to change it and/or let me know!

I have created a global variable `g:CtrlXA_iskeyword` to collect the values from `l:iskeyword` as a default behaviour. If the user does not set `b:CtrlXA_iskeyword`, then `g:CtrlXA_iskeyword` is used. But if the user uses the buffer-specific version `b:CtrlXA_iskeyword`, then that one is used.

**Comment by Konfekt** [comment]
Thank you!  I am sorry, I misunderstood `could collect the values from iskeyword`. 
`g:CtrlXA_iskeyword` should default to all the characters that appear in the keyword list instead of `&iskeyword` to add some value (for example, solve this issue), but I know of no reference for such a character collection function.

**Comment by mgarort** [comment]
I thought that the value of `g:CtrlXA_iskeyword` was so that people could set toggle delimiters different from `iskeyword` in every filetype. Otherwise, they would have to set up an autocommand to define `b:CtrlXA_iskeyword` every time a buffer is open or something like that.

But in any case, I am happy enough with just `b:CtrlXA_iskeyword` because I work with just 3-4 filetypes. So as far as I am concerned this issue can be closed.

Thanks a lot for implementing the changes so quickly! :)

**Comment by Konfekt** [comment]
True, forgot that. Thank you! I was afraid of some doubling, but it is further enhancement.

Still, this issue piqued my interest to define `&iskeyword` minimally, that is, by only those characters appearing in the keyword list.
I guess asking for it on Vim exchange would yield a short solution, but will think about it a bit in the meanwhile.

**Comment by mgarort** [comment]
I think there is a bug related to the new functionality (sorry! :/ ).

At the beginning of the function `CtrlXA#SingleInc` in `autoload`, the setting `iskeyword` is set to `CtrlXA_iskeyword`, but after completion it is not reset back to its original value. So after pressing `<C-x>` or `<C-a>`, `iskeyword` stays modified and the definition of a word changes forever.

I have tried to fix it myself by saving the original value of `iskeyword` to a temporary variable `l:old_iskeyword`, and restoring it right at the end of the function `CtrlXA#SingleInc` with `let &l:iskeyword = l:old_iskeyword`. Unfortunately this doesn't work, presumably because the funtion reaches some `return` statement and finishes before it can restore the original value. I don't know how to proceed because I don't really understand the nuts and bolts of the function, so I'm not sure at which point it should be restored.

**Comment by Konfekt** [comment]
I think `&l:iskeyword`, a buffer local variable, was mixed up with `l:iskeyword`, a function local variable and hope to have just fixed it.

**Comment by mgarort** [comment]
Thanks a lot! I have finally gotten the time to test it.

- `b:CtrlXA_iskeyword` doesn't seem to make a difference now. (Maybe this change was intentional? Not sure.)
- `g:CtrlXA_iskeyword` works, but as soon as `<C-a>` or `<C-x>` are used, the setting `iskeyword` changes forever, and is not restored. So in my case, because `g:CtrlXA_iskeyword` is set to not include `_` (in order to separate `max` from `x` in `max_x`), `iskeyword` doesn't include `_` after using `<C-a>` or `<C-x>`.

**Comment by Konfekt** [comment]
Thank you for testing. Indeed, there were return statements before restoring `&iskeyword`. The last commit should fix it. Please give it another whirl.

**Comment by mgarort** [comment]
Great, thanks a lot :)  I think it is fixed now. Using `<C-a>` and `<C-x>` doesn't affect `iskeyword`, and both `b:CtrlXA_iskeyword` and `g:CtrlXA_iskeyword` work correctly.

**Comment by mgarort** [comment]
I realized that `iskeyword` was still changed when the toggle was a number. So, for example, doing `<C-a>` on `1` would change `iskeyword`, but doing `<C-a>` on `x` did not change it. I've submitted a pull request that should fix it, i.e. should restore `iskeyword` for every toggle so that it never changes.

**Comment by Konfekt** [comment]
True; please give it another try.
