### ISSUE TITLE
Custom map and speeddating

### ISSUE THREAD

**Issue by patnr** [Konfekt/vim-CtrlXA#15]
Hi! I use the following

```vim
nmap <up>   <Plug>(CtrlXA-CtrlA)
nmap <down> <Plug>(CtrlXA-CtrlX)
nmap <Plug>SpeedDatingFallbackUp   <Plug>(CtrlXA-CtrlX)
nmap <Plug>SpeedDatingFallbackDown <Plug>(CtrlXA-CtrlA)
```

However, when I put my cursor on (e.g.) `31`  in `1998-12-31` the speeddating functionality only works if using the standard maps (`ctrl-x`/`ctrl-a`), while my custom maps (`up`/`down`) treat `31` as a number.

Is this supposed to work? Maybe I'm configuring it wrong?

**Comment by Konfekt** [comment]
Looking at the [source](https://github.com/tpope/vim-speeddating/blob/fe98cfaa7ea9c4b838d42a6830437c919eb55b4e/plugin/speeddating.vim#L50) this seemingly will only be possible once https://github.com/tpope/vim-speeddating/pull/26 merged.

**Comment by Konfekt** [comment]
Solved by

```vim
nmap <Up>   <Plug>SpeedDatingUp
nmap <Down> <Plug>SpeedDatingDown
nmap <Plug>SpeedDatingFallbackUp   <Plug>(CtrlXA-CtrlX)
nmap <Plug>SpeedDatingFallbackDown <Plug>(CtrlXA-CtrlA)
```

See https://github.com/tpope/vim-speeddating/pull/26#issuecomment-829107084

**Comment by patnr** [comment]
Brilliant! Thanks a lot!

PS: the `CtrlX` mappings should be swapped:

```vim
let g:speeddating_no_mappings = 1
nmap <Up>   <Plug>SpeedDatingUp
nmap <Down> <Plug>SpeedDatingDown
nmap <Plug>SpeedDatingFallbackUp   <Plug>(CtrlXA-CtrlA)
nmap <Plug>SpeedDatingFallbackDown <Plug>(CtrlXA-CtrlX)
```
