### ISSUE TITLE
Question: Logic of Roman numeral increment

### ISSUE THREAD

**Issue by ajitid** [Konfekt/vim-CtrlXA#17]
I'm curious, how this plugin is able to correctly increment Roman numerals after IX given that only I to IX numerals are defined in `g:CtrlXA_Toggles`?

**Comment by Konfekt** [comment]
It is possible.  For this `X` needs to be removed from the alphabet toggle list `['A', ..., 'X', 'Y', 'Z']` and `X` added to the roman numeral list `['I', ..., 'IX' ]`.

**Comment by ajitid** [comment]
No, no that's what not I'm saying. With the default value in `g:CtrlXA_Toggles` your plugin is properly able to increment/decrement values that fall outside I - IX range which I'm not able to understand how your plugin is able to do it.

![Animation](https://user-images.githubusercontent.com/26769888/118832164-3f713400-b875-11eb-8078-258942f66e33.gif)

**Comment by ajitid** [comment]
Oh it's inbuilt in Vim! 😂 

Closing the issue.

**Comment by Konfekt** [comment]
Oh, must be a recent addition to Vim.

**Comment by ajitid** [comment]
Yeah, just to complete what I said, I'm using latest build of Neovim 0.5.
