### ISSUE TITLE
Question: does it work with tpope/vim-speeddating?

### ISSUE THREAD

**Issue by PauloPhagula** [Konfekt/vim-CtrlXA#5]
Does this plugin integrate well with https://github.com/tpope/vim-speeddating?

**Comment by Konfekt** [comment]
Yes, thanks to https://github.com/tpope/vim-speeddating/commit/a418667791f03694065948342f2d6c5cca8d0f32 by adding
```vim  
nmap <Plug>SpeedDatingFallbackUp <Plug>(CtrlXA-CtrlA)
nmap <Plug>SpeedDatingFallbackDown <Plug>(CtrlXA-CtrlX)
```
to your `.vimrc` it falls back to the mappings set up by this plug-in.

**Comment by Konfekt** [comment]
It is now documented. Let me know how it goes.

**Comment by PauloPhagula** [comment]
Works wonders, thanks!
