### ISSUE TITLE
FYI: cross-match in default config lists

### ISSUE THREAD

**Issue by cometsong** [Konfekt/vim-CtrlXA#6]
FYI, The two lists (upper/lower-case) of the Roman numerals and the alphabet letters have crossover matches, e.g. 'i', 'v', and the 'x' I added in to the Roman lists.

```vim
  ['i', 'ii', 'iii', 'iv', 'v', 'vi', 'viii'],
  ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
```
Of course people are *expected* (or at least *able*) to overwrite these defaults... 😉 

Otherwise, this is an *awesome* plugin!

**Comment by Konfekt** [comment]
Thanks! Yeah, true! I found that the precedence given to the Roman numeral cycles is also mine, so as a benevolent dictator I leave it at that. I will pull them out and comment on this preference.

**Comment by Konfekt** [comment]
Done in  bcb14182f06789f212c1930e79ab659e41f3f602
