### ISSUE TITLE
keep the default while setting my own

### ISSUE THREAD

**Issue by teto** [Konfekt/vim-CtrlXA#7]
Great plugin/idea.

I want to keep the defaults while appending my own.
Using an autocmd seems superfluous. Any way CtrlXA can append my config to its default ?

**Comment by Konfekt** [comment]
Yes, there is. Say you want to add the pair `['maximize', 'minimize']`. Then put
```vim
let g:CtrlXA_Toggles = [
      \ ['maximize', 'minimize'],
      \ ] + g:CtrlXA_Toggles
```
into `~/.vim/after/plugin/CtrlXA.vim`, or, alternatively,
```vim
  augroup VimAfter
    autocmd!
    autocmd VimEnter let let g:CtrlXA_Toggles = [
      \ ['maximize', 'minimize'],
      \ ] + g:CtrlXA_Toggles
  augroup END
```
into your `vimrc`.

**Comment by Konfekt** [comment]
See the updated README and doc.txt.

**Comment by teto** [comment]
nice indeed; I've added `after/plugin/CtrlXA.vim`
```
let g:CtrlXA_Toggles += [ 
  \ [ 'MPTCP', '\gls{mptcp}' ]
  \ ]

```
While I could convert MPTCP into \gls{mptcp}, I could not cycle back to MPTCP. I suppose it depends on some parameter :) doesn't matter much still very useful. Thanks !

**Comment by Konfekt** [comment]
This looks like a file type specific pair. In this case, have a glimpse at https://github.com/Konfekt/vim-CtrlXA#buffer-local-configuration . For example
```vim
autocmd FileType tex
              \ let b:CtrlXA_Toggles = [
              \ ['final', 'draft'],
              \ ] + g:CtrlXA_Toggles
```
in a TeX file type.

**Comment by teto** [comment]
dunno why, I haven't changed anything but now works both ways. Very cool xD thanks again
