### ISSUE TITLE
dont move cursor

### ISSUE THREAD

**Issue by teto** [Konfekt/vim-CtrlXA#8]
after toggling a word cursor moves to the end of the word which I find annoying, would it be possible to keep the cursor in place please ?

btw I had no idea how useful the idea was before installing this plugin, I really love it and ended up using much more than I thought.

**Comment by Konfekt** [comment]
Thanks for the kind words! Vim also moves the cursor to the end of the incremented value, for example, with `*` denoting the cursor column,
```
*
The number is 99.
```
becomes, after hitting `<Ctrl-A`>
```
                            *
The number is 100.
```

Still, I changed the behavior for words, but left Vim's defaults for numbers intact, as this plug-in should only nonintrusively enhance Vim's functions.

**Comment by Konfekt** [comment]
Thanks for the suggestion! After all, seems like a more sensible behavior. Let's see how it goes.

**Comment by teto** [comment]
thanks !
